# Generated by Django 4.1.1 on 2022-10-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryActiondb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('dlid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.licensedb')),
            ],
        ),
    ]
