# Generated by Django 4.1.1 on 2022-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurancedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default=0, max_length=100)),
                ('engine_no', models.CharField(default=0, max_length=13)),
                ('chassis_no', models.CharField(default=0, max_length=17)),
                ('registration_no', models.CharField(default=0, max_length=10)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
    ]
