# Generated by Django 4.1.1 on 2022-10-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRegisterdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
