# Generated by Django 4.1.1 on 2022-10-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regisdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=25)),
                ('phonenumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=15)),
                ('username', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rc_Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_no', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(max_length=20)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.rcdetailsdb')),
                ('userdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PublicApp.regisdb')),
            ],
        ),
        migrations.CreateModel(
            name='Dl_Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=20)),
                ('dlid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.licensedb')),
                ('userdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PublicApp.regisdb')),
            ],
        ),
    ]
