# Generated by Django 4.1.1 on 2022-10-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaintdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('color', models.CharField(max_length=10)),
                ('Body_style', models.CharField(max_length=10)),
                ('marker_platenumber', models.CharField(max_length=10)),
                ('vehicle_registered', models.BooleanField()),
                ('vehicle_register_state', models.CharField(max_length=10)),
                ('door_locked', models.BooleanField()),
                ('keys_invehicle', models.BooleanField()),
                ('nameof_owner', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('court_available', models.BooleanField()),
                ('date_vehicle_stolen', models.DateField()),
                ('vehicle_identification_number', models.IntegerField()),
                ('nameof_insurance_company', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('dateof_stolen', models.IntegerField()),
                ('dayof_week', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('location_from', models.CharField(max_length=10)),
            ],
        ),
    ]
