# Generated by Django 4.1.1 on 2022-10-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0002_complaintdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdb',
            name='dateof_stolen',
        ),
    ]
