# Generated by Django 4.1.1 on 2022-10-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licensedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivinglicenseNo', models.CharField(max_length=30)),
                ('holder_name', models.CharField(max_length=20)),
                ('license_authority', models.CharField(max_length=30)),
                ('vehicle_class', models.CharField(max_length=30)),
                ('issue_date', models.DateField(null=True)),
                ('license_validity', models.DateField(null=True)),
                ('dob', models.DateField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RcDetailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default=0, max_length=100)),
                ('registered_rto', models.CharField(default=0, max_length=50)),
                ('maker_model', models.CharField(default=0, max_length=13)),
                ('vehicle_class', models.CharField(default=0, max_length=50)),
                ('fuel_norms', models.CharField(default=0, max_length=30)),
                ('engine_no', models.CharField(default=0, max_length=13)),
                ('chassis_no', models.CharField(default=0, max_length=17)),
                ('registration_date', models.DateField(default=0)),
                ('fitness_upto', models.DateField(default=0)),
                ('insurance_expiry', models.DateField(default=0)),
                ('insurance_expiry_in', models.DateField(default=0)),
                ('registration_no', models.CharField(default=0, max_length=10)),
                ('color', models.CharField(default=0, max_length=20)),
                ('unloaded_weight', models.IntegerField()),
            ],
        ),
    ]
