# Generated by Django 4.1.1 on 2022-10-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutiondb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(default=0, max_length=100)),
                ('vehicle_make', models.CharField(default=0, max_length=20)),
                ('vehicle_model', models.CharField(default=0, max_length=20)),
                ('yearof_manufacture', models.CharField(default=0, max_length=10)),
                ('typeof_vehicle', models.CharField(default=0, max_length=50)),
                ('typeof_engine', models.CharField(default=0, max_length=20)),
                ('id_number', models.CharField(default=0, max_length=20)),
                ('engine_no', models.CharField(default=0, max_length=20)),
                ('speedo_meter', models.CharField(default=0, max_length=10)),
                ('date', models.DateField()),
                ('fuel', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionRegisterdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
